# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - develop
      - staging
      - main
  review_status: true
