export enum EmailNameEnum {
  FORGOT_PASSWORD = 'Forgot Password',
  USER_REGISTERED_ADMIN = 'User Registered Admin',
  USER_REGISTERED_USER = 'User Registered User',
  USER_REGISTERED_PARTNER = 'User Registered Partner',
  SUPPORT_EMAIL_ADMIN = 'Support Email Admin',
  SUPPORT_EMAIL_CLIENT = 'Support Email Client',
  ADMIN_APPROVAL = 'Admin Approval',
  ACCOUNT_MANAGER_INVITE = 'Account Manager Invite',
  PAYMENT_FAILED = 'Payment Failed',
  USER_DEACTIVATED = 'User Deactivated',
  USER_ACTIVATED = 'User Activated',
  USER_SUSPENDED = 'User Suspended',
  USER_UNSUSPENDED = 'User Unsuspended',
  USER_ACCOUNT_DEACTIVATED = 'User Account Deactivated',
  USER_ACCOUNT_ABANDONED = 'User Account Abandoned',
  USER_ACCOUNT_DELETED = 'User Account Deleted',
  CRM_AGENT_SIGNUP = 'CRM Agent Signup',
}
